[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "backend"
source = "server"

[[services]]
name = "frontend"
source = "."